# Generated by Django 5.2.12 on 2026-09-16 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('asset_class', models.CharField(choices=[('Equity', 'Equity'), ('ETF', 'ETF'), ('Fixed Income', 'Fixed Income'), ('Commodity', 'Commodity'), ('Currency', 'Currency'), ('Other', 'Other')], default='Equity', max_length=30)),
                ('sector', models.CharField(blank=True, max_length=60)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, default='United States', max_length=40)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('is_factor_etf', models.BooleanField(default=False, help_text='Used to build the ETF factor model')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('cash', models.FloatField(default=0.0, help_text='Cash balance; negative means borrowed')),
                ('benchmark', models.CharField(default='SPY', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Overrides for analytics: lookback_days, cov_method, var_confidence, target_beta ...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='core.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('gross_exposure', 'Gross exposure (% NAV)'), ('net_exposure', 'Net exposure (% NAV)'), ('long_exposure', 'Long exposure (% NAV)'), ('short_exposure', 'Short exposure (% NAV)'), ('position_weight', 'Single position |weight| (% NAV) - scope: ticker or blank for max'), ('sector_gross', 'Sector gross exposure (% NAV) - scope: sector'), ('sector_net', 'Sector net exposure (% NAV) - scope: sector'), ('beta', 'Beta to benchmark'), ('vol', 'Annualised volatility'), ('var', 'Value at Risk (% NAV, portfolio confidence/horizon)'), ('cvar', 'Expected shortfall (% NAV)'), ('top5_weight', 'Top-5 positions share of gross'), ('max_risk_share', 'Largest single-name share of volatility'), ('effective_n', 'Effective number of positions'), ('days_to_liquidate', 'Days to liquidate (worst, or scope: ticker)'), ('factor_beta', '|Factor beta| - scope: factor name'), ('stress_loss', 'Worst stress scenario loss (% NAV)'), ('drawdown', 'Current pro-forma drawdown (% NAV)')], max_length=40)),
                ('scope', models.CharField(blank=True, help_text='Ticker, sector or factor, depending on metric', max_length=60)),
                ('operator', models.CharField(choices=[('lte', 'must be <='), ('gte', 'must be >=')], default='lte', max_length=3)),
                ('threshold', models.FloatField(help_text='Fractions for percentages (0.25 = 25%)')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='core.portfolio')),
            ],
            options={
                'ordering': ['metric', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='draft', max_length=10)),
                ('source', models.CharField(blank=True, help_text='manual | optimizer:<method> | sizing', max_length=40)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Before/after metrics captured at creation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.FloatField(help_text='Shares to buy (+) or sell (-)')),
                ('limit_price', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asset')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.tradeproposal')),
            ],
            options={
                'ordering': ['asset__ticker'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Shares/units; negative = short')),
                ('avg_cost', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.portfolio')),
            ],
            options={
                'ordering': ['asset__ticker'],
                'unique_together': {('portfolio', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.asset')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='core_price_date_b2a621_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.portfolio')),
            ],
            options={
                'ordering': ['as_of'],
                'unique_together': {('portfolio', 'as_of')},
            },
        ),
    ]
